const ACTIONS = {
	SIGNIN: 'SIGNIN',
	GET_TOKEN: 'GET_TOKEN',
	GET_USER: 'GET_USER',
	GET_SALON: 'GET_SALON',
	GET_VISIT: 'GET_VISIT',
	GET_SALON_ID: 'GET_SALON_ID',
	GET_SERVICE_ID: 'GET_SERVICE_ID',
	GET_CUSTOM_SERVICE: 'GET_CUSTOM_SERVICE',
};

export default ACTIONS;
